"""empty message

Revision ID: 78642a14f0f3
Revises: 25d401a74c6d
Create Date: 2022-08-12 06:57:41.835685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78642a14f0f3'
down_revision = '25d401a74c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'image_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
